export const headphones: Headphone[] = [
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-69.png',
    tags: [],
    name: 'RY4S',
    signature: 'Natural',
    price: 58,
    overview: 'Um earbud incrível e muito barato.',
    buy: 'https://s.click.aliexpress.com/e/_AgoVXj',
    review: 'https://youtu.be/EpU1_q5KMFE',
    category: 'Earbud'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-3-1.png',
    tags: [],
    name: 'Lenovo GM2 Pro',
    signature: 'Natural',
    price: 62,
    overview: 'Acho que nunca vou entender como esse fone é possível.',
    buy: 'https://s.click.aliexpress.com/e/_oF0RaMu',
    review: 'https://youtu.be/QoWY7vkh_3g',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-48.png',
    tags: [],
    name: 'CCA CRA',
    signature: 'Enérgico',
    price: 72,
    overview: 'Se você quiser gastar pouco e quiser uma sonoridade viva e energética.',
    buy: 'https://s.click.aliexpress.com/e/_9wFJr7',
    review: 'https://youtu.be/KW0RU9CtPIw',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-106.png',
    tags: [],
    name: 'QKZ x HBB',
    signature: 'Basshead',
    price: 84,
    overview: 'Pra quem quer grave pra caramba, sem gastar muito.',
    buy: 'https://s.click.aliexpress.com/e/_olZUBNF',
    review: 'https://youtu.be/Vo3-XIjqhZs',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-108.png',
    tags: [],
    name: 'KZ ZSN Pro',
    signature: 'V-Shaped Forte',
    price: 101,
    overview: 'Enérgico pra caramba, custando pouco.',
    buy: 'https://s.click.aliexpress.com/e/_oCdLq5J',
    review: 'https://youtu.be/S9Jo-znQrnk',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-41.png',
    tags: [],
    name: 'Redmi Buds 6 Active',
    signature: 'Natural',
    price: 110,
    overview: 'Se você não se incomodar com o volume mais baixo, até melhor que o QCY T20.',
    buy: 'https://s.click.aliexpress.com/e/_DD9W2Fr',
    review: 'https://youtu.be/AJSEmxiIp4g',
    category: 'Earbud Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-47.png',
    tags: ['Favorito do canal'],
    name: 'Moondrop Chu II',
    signature: 'Natural',
    price: 132,
    overview: 'O melhor in-ear em torno de R$100.',
    buy: 'https://s.click.aliexpress.com/e/_DD7BdAT',
    review: 'https://youtu.be/tgcV8NZS3ho',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-73.png',
    tags: [],
    name: 'QCY T20',
    signature: 'Natural',
    price: 146,
    overview: 'Um excelente TWS em formato de earbud.',
    buy: 'https://s.click.aliexpress.com/e/_DdoXtRd',
    review: 'https://youtu.be/OhOwMV5yTxA',
    category: 'Earbud Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-6-1.png',
    tags: [],
    name: 'Kawano Audio Horaiko',
    signature: 'Neutro-Quente',
    price: 150,
    overview: 'Projeto artesanal, feito no Brasil. Sensacional!',
    buy: 'https://www.kawanoaudio.com',
    review: 'https://youtu.be/WBGbNFZNPvE',
    category: 'Earbud'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-16.png',
    tags: [],
    name: 'Havit H630BT',
    signature: 'Natural',
    price: 158,
    overview: 'Um fone bluetooth extremamente acessível, com sonoridade legal. E tem rádio!',
    buy: 'https://youtu.be/HuNNC9B6S0Y',
    review: 'https://s.zbanx.com/r/1G7fQ37Ye25E',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-2-1.png',
    tags: [],
    name: 'QCY T13 ANC',
    signature: 'Natural',
    price: 165,
    overview: 'Um belo sucessor do incrível T13 ANC. Relação custo-benefício inacreditável.',
    buy: 'https://s.click.aliexpress.com/e/_oDD7t5O',
    review: 'https://youtu.be/fWOAdu48rtw',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-17.png',
    tags: [],
    name: 'Arcano AR-414B',
    signature: 'Neutro-Quente',
    price: 170,
    overview: 'Envolvente e muito competente para um fone bluetooth tão barato (use o cupom MINDTHEHEADPHONE).',
    buy: 'https://www.lojadiscovery.com.br/ar-414b',
    review: 'https://youtu.be/B1GwNqSl62w',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-61.png',
    tags: [],
    name: 'Anker Soundcore P20i',
    signature: 'Enérgico',
    price: 182,
    overview: 'Consideravelmente mais divertido que o Space Travel, porém menos natural.',
    buy: 'https://s.zbanx.com/r/QzIHFpvaxEKB',
    review: 'https://youtu.be/eslfbd_DepM',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-88.png',
    tags: [],
    name: 'Moondrop Chu',
    signature: 'Neutro-Frio',
    price: 190,
    overview: 'Mais frio que o Chu 2, mas ainda excepcionalmente natural.',
    buy: 'https://s.click.aliexpress.com/e/_oBPtIhR',
    review: 'https://youtu.be/XXncYp0M0NU',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-5.png',
    tags: [],
    name: 'Havit Fuxi-H3',
    signature: 'Natural',
    price: 193,
    overview: 'Muitas opções de conectividade. Pode ser bem interessante pra jogos por conta disso.',
    buy: 'https://s.zbanx.com/r/7YDkD33Cs90e%20%20%20%20',
    review: 'https://youtu.be/HuNNC9B6S0Y',
    category: 'Headphone Gamer'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-42.png',
    tags: [],
    name: 'Huawei Freebuds 2SE',
    signature: 'Enérgico',
    price: 199,
    overview: 'Uma opção mais equilibrada ao QCY T20, que é mais cheio.',
    buy: 'https://s.zbanx.com/r/4jHv5K88a66w',
    review: 'https://youtu.be/o-4htA1U2LM',
    category: 'Earbud Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-68.png',
    tags: [],
    name: 'QCY HT10',
    signature: 'Natural',
    price: 199,
    overview: 'Médios bem melhores que o T20, graves e agudos melhores que o Freebuds 2SE',
    buy: 'https://amzn.to/3SRORmn',
    review: 'https://youtu.be/1EGGBnM_7FM',
    category: 'Earbud Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-6.png',
    tags: [],
    name: 'Havit H2002D',
    signature: 'Natural',
    price: 199,
    overview: 'Sonoridade mais quente, surpreendentemente boa para um fone nessa faixa de preço.',
    buy: 'https://s.zbanx.com/r/JC3c5NPl065Q',
    review: 'https://youtu.be/HuNNC9B6S0Y',
    category: 'Headphone Gamer'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-98.png',
    tags: [],
    name: 'Moondrop Space Travel',
    signature: 'Natural',
    price: 207,
    overview: 'Não é a maior bateria da categoria, mas é o melhor som.',
    buy: 'https://s.click.aliexpress.com/e/_DEfaQRV',
    review: 'https://youtu.be/UYwz7aItYuQ',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-103.png',
    tags: [],
    name: 'OneOdio Pro-10',
    signature: 'Neutro-Quente',
    price: 207,
    overview: 'Headphone barato muito competente, apesar dos graves fortes demais.',
    buy: 'https://s.click.aliexpress.com/e/_A5LlPK',
    review: 'https://youtu.be/Sjv257nTm4M',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-75.png',
    tags: [],
    name: 'Tin Hifi C2 Mech Warrior',
    signature: 'Natural',
    price: 215,
    overview: 'Uma opção mais eufônica ao ZS10 Pro X',
    buy: 'https://s.click.aliexpress.com/e/_DEmpPfj',
    review: 'https://youtu.be/s6NbmtO905I',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-104.png',
    tags: [],
    name: 'Arcano SHP80',
    signature: 'Neutro-Frio',
    price: 235,
    overview: 'Confortável e com sonoridade aberta e arejada (use o cupom MINDTHEHEADPHONE).',
    buy: 'https://www.lojadiscovery.com.br/arc-shp80',
    review: 'https://youtu.be/08sU1AYHX8s',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-5-1.png',
    tags: [],
    name: 'Kawano Audio Hanabi',
    signature: 'Neutro-Quente',
    price: 250,
    overview: 'Projeto artesanal, feito no Brasil. Sensacional!',
    buy: 'https://www.kawanoaudio.com',
    review: 'https://youtu.be/WBGbNFZNPvE',
    category: 'Earbud'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-89.png',
    tags: [],
    name: 'Blon Z300',
    signature: 'Neutro-Quente',
    price: 256,
    overview: 'Caloroso do jeito certo. Fantástico pra gêneros mais pesados.',
    buy: 'https://s.click.aliexpress.com/e/_oEU4PfR',
    review: 'https://youtu.be/yXIVWHolcho',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-97.png',
    tags: [],
    name: 'QCY MeloBuds Pro',
    signature: 'Natural',
    price: 262,
    overview: 'Belíssimo conjunto pelo preço, com som bem envolvente.',
    buy: 'https://s.click.aliexpress.com/e/_DmGiIQN',
    review: 'https://youtu.be/G72tDT2FqTc',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-67.png',
    tags: [],
    name: 'Arcano SHP300',
    signature: 'Neutro-Quente',
    price: 280,
    overview: 'Sonoridade viva e energética (use o cupom MINDTHEHEADPHONE).',
    buy: 'https://www.lojadiscovery.com.br/arc-shp300',
    review: 'https://youtu.be/2uIE9rXdfYI',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-46.png',
    tags: [],
    name: 'KZ ZS10 Pro X',
    signature: 'Enérgico',
    price: 289,
    overview: 'Finalmente, a KZ de volta no jogo. A incrível releitura de um fone lendário. Excepcional.',
    buy: 'https://s.click.aliexpress.com/e/_DCEASFV',
    review: 'https://youtu.be/F8SRRMTV1vY',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-15.png',
    tags: [],
    name: 'Havit H655BT',
    signature: 'Natural',
    price: 299,
    overview: 'Boa opção pra quem quer um fone bluetooth com cancelamento de ruídos super barato.',
    buy: 'https://mercadolivre.com/sec/1nAZwaE',
    review: 'https://youtu.be/qZKF7c7IJzk',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-93.png',
    tags: [],
    name: 'Tin Hifi T2',
    signature: 'Neutro-Frio',
    price: 306,
    overview: 'Um dos grandes marcos do movimento chi-fi. Incrivelmente delicado e envolvente.',
    buy: 'https://s.click.aliexpress.com/e/_oke9qzB',
    review: 'https://youtu.be/JkBxCTrqeWY',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-110.png',
    tags: [],
    name: 'KZ ZAR',
    signature: 'Basshead',
    price: 375,
    overview: 'Um belo basshead da KZ.',
    buy: 'https://s.click.aliexpress.com/e/_opsqCnF',
    review: 'https://youtu.be/ai-ecH6i5s8',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-14.png',
    tags: [],
    name: 'Edifier W800BT Plus',
    signature: 'Natural',
    price: 399,
    overview: 'Fone equilibrado e competente.',
    buy: 'https://amzn.to/3saRIvY',
    review: 'https://youtu.be/bkgr2ND_zPM',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-13.png',
    tags: [],
    name: 'Edifier W820NB',
    signature: 'Natural',
    price: 399,
    overview: 'Incrível pelo que custa. Sonoridade equilibrada e interessante.',
    buy: 'https://amzn.to/3Q3LpCJ',
    review: 'https://youtu.be/ehJTwlmTfzU',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-74.png',
    tags: [],
    name: 'Armer SH450',
    signature: 'Neutro-Quente',
    price: 400,
    overview: 'Intenso porém equilibrado. Pegada mais fechada.',
    buy: 'https://amzn.to/42VcNY44',
    review: 'https://youtu.be/1g5FgBkeBlY',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-96.png',
    tags: [],
    name: 'KZ Xtra',
    signature: 'Neutro-Frio',
    price: 403,
    overview: 'Um dos TWS que menos soa como um TWS. Fantástico, com som mais aberto e transparente.',
    buy: 'https://s.click.aliexpress.com/e/_DFjDYRR',
    review: 'https://youtu.be/Bo6SCuzoAaQ',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-99.png',
    tags: [],
    name: 'Redmi Buds 5 Pro',
    signature: 'Natural',
    price: 404,
    overview: 'Alternativa com mais recursos ao KZ Xtra, porém com som tecnicamente inferior',
    buy: 'https://s.click.aliexpress.com/e/_DcQHny9',
    review: 'https://youtu.be/AJSEmxiIp4g',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-12.png',
    tags: [],
    name: 'Haylou S30 Pro',
    signature: 'Natural',
    price: 427,
    overview: 'Bela opção para home-office, com o microfone destacável.',
    buy: 'https://s.click.aliexpress.com/e/_DElyeHZ',
    review: 'https://youtu.be/richJiDWQcU',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-66.png',
    tags: [],
    name: 'Samsung Galaxy Buds Live',
    signature: 'Neutro-Quente',
    price: 449,
    overview: 'Ainda muito bom, porém fora de produção.',
    buy: 'https://amzn.to/3MGyNhK',
    review: 'https://youtu.be/BYfCV-bQv6w',
    category: 'Earbud Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-4.png',
    tags: [],
    name: 'Pichau P852 Atria',
    signature: 'Natural',
    price: 450,
    overview: 'Boa opção de headset acessível com desempenho competente.',
    buy: 'https://bit.ly/3MkBPIg',
    review: 'https://youtu.be/buL8jbMxFyo',
    category: 'Headphone Gamer'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-60.png',
    tags: [],
    name: 'Anker X10',
    signature: 'Natural',
    price: 490,
    overview: 'Requer equalização pra ficar legal, mas é ótimo para exercícios pelo design e resistência.',
    buy: 'https://s.click.aliexpress.com/e/_DEEWEyJ',
    review: 'https://youtu.be/eslfbd_DepM',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-109.png',
    tags: [],
    name: 'Truthear Zero',
    signature: 'Basshead',
    price: 523,
    overview: 'Sonoridade em tese Harman, mas me parece bem gravudo.',
    buy: 'https://s.click.aliexpress.com/e/_oDAqbJn',
    review: 'https://youtu.be/8JBKJPWboWo',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-2.png',
    tags: [],
    name: 'HyperX Cloud Core',
    signature: 'Natural',
    price: 539,
    overview: 'Um clássico headset.',
    buy: 'https://amzn.to/328j9tH',
    review: '',
    category: 'Headphone Gamer'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-3.png',
    tags: [],
    name: 'Pichau P852 Vega',
    signature: 'Natural',
    price: 550,
    overview: 'Quase igual ao Atria, porém USB, com equalizador e um efeito surround sutil e interessante.',
    buy: 'https://bit.ly/35RAXv5',
    review: 'https://youtu.be/buL8jbMxFyo',
    category: 'Headphone Gamer'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-65.png',
    tags: [],
    name: 'Anker Soundcore Space A40',
    signature: 'Neutro-Frio',
    price: 555,
    overview: 'Personalidade mais espacial e eufônica.',
    buy: 'https://s.zbanx.com/r/uMDDYDUwu4gN',
    review: 'https://youtu.be/eslfbd_DepM',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-50.png',
    tags: ['Favorito do canal'],
    name: 'Truthear Zero:RED',
    signature: 'Natural',
    price: 566,
    overview: 'Absolutamente incrível. Para os meus ouvidos, melhor até que o Hexa.',
    buy: 'https://s.click.aliexpress.com/e/_DdwwTgZ',
    review: 'https://youtu.be/8JBKJPWboWo',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-8-1.png',
    tags: [],
    name: 'Anker Soundcore Liberty 4NC',
    signature: 'Natural',
    price: 566,
    overview: 'Conjunto excepcional pelo que custa: construção, recursos, som e conforto.',
    buy: 'https://s.click.aliexpress.com/e/_omQqKWG',
    review: 'https://youtu.be/Yvfwc-KJD-s',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-51.png',
    tags: [],
    name: 'Moondrop May',
    signature: 'Natural',
    price: 577,
    overview: 'Muito natural, com os recursos do cabo DSP.',
    buy: 'https://s.click.aliexpress.com/e/_DlWwVVN',
    review: 'https://youtu.be/ZXlejDD-toA',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-10-1.png',
    tags: [],
    name: 'FiiO JT1',
    signature: 'Neutro-Quente',
    price: 577,
    overview: 'Uma alternativa mais musical e eufônica ao Hifiman HE400SE.',
    buy: 'https://s.click.aliexpress.com/e/_DnFOj1R',
    review: 'https://youtu.be/XO6nbeduc2o',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-70.png',
    tags: [],
    name: 'Philips SHP9500',
    signature: 'Analítico',
    price: 591,
    overview: 'Muito detalhado, porém com pouco grave.',
    buy: 'https://s.click.aliexpress.com/e/_AW1L4F',
    review: 'https://youtu.be/duTiBYfhLZQ',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-43.png',
    tags: [],
    name: 'Huawei Freebuds 6i',
    signature: 'Natural',
    price: 599,
    overview: 'Um dos melhores cancelamentos ativos de ruídos pelo preço.',
    buy: 'https://amzn.to/4fz38wS',
    review: 'https://youtu.be/b1tjbmkjvKA',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-38.png',
    tags: [],
    name: 'Kuba Nia Lite',
    signature: 'Enérgico',
    price: 599,
    overview: 'Minha própria marca.',
    buy: 'https://kuba.audio/products/nia?variant=49525569225019',
    review: 'https://youtu.be/CUE_Cy5gaaE',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-11.png',
    tags: [],
    name: 'Anker Soundcore Q30',
    signature: 'Basshead',
    price: 612,
    overview: 'Semelhante ao W820NB, porém com melhor construção. Requer equalização.',
    buy: 'https://s.click.aliexpress.com/e/_AAN4nF',
    review: 'https://youtu.be/KPn8sV8bf4c',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-40.png',
    tags: [],
    name: 'Huawei Freebuds 5',
    signature: 'Natural',
    price: 649,
    overview: 'Envolvente e divertido. Excelente pelo preço.',
    buy: 'https://amzn.to/3Fm0XNe',
    review: 'https://youtu.be/I9oflmOAJRU',
    category: 'Earbud Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-37.png',
    tags: [],
    name: 'Kuba Nia Headset',
    signature: 'Enérgico',
    price: 649,
    overview: 'Minha própria marca.',
    buy: 'https://kuba.audio/products/nia?variant=49525569225019',
    review: 'https://youtu.be/CUE_Cy5gaaE',
    category: 'Headphone Gamer'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-39.png',
    tags: [],
    name: 'Hifiman HE400SE',
    signature: 'Seco/Direto',
    price: 666,
    overview: 'Um fantástico planar de entrada e uma verdadeira barganha.',
    buy: 'https://s.click.aliexpress.com/e/_A5cSPA',
    review: 'https://youtu.be/hQHY2pngXHA',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-101.png',
    tags: [],
    name: 'Samsung Galaxy Buds2 Pro',
    signature: 'Natural',
    price: 698,
    overview: 'Sonoridade Harman e uma bela relação custo-benefício.',
    buy: 'https://amzn.to/3YxkbZC',
    review: 'https://youtu.be/SYgYoC6b9Mk',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-72.png',
    tags: [],
    name: 'Armer SH550',
    signature: 'Neutro-Frio',
    price: 699,
    overview: 'Intenso porém equilibrado. Pegada mais aberta.',
    buy: 'https://amzn.to/3NMo0G2',
    review: 'https://youtu.be/1g5FgBkeBlY',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-102.png',
    tags: [],
    name: 'Dunu Alpha 3',
    signature: 'Natural',
    price: 741,
    overview: 'Melhor que o RY4S em linearidade e transparência, porém muito mais caro.',
    buy: 'https://s.click.aliexpress.com/e/_DE365nd',
    review: 'https://youtu.be/ENL1PZ0U62I',
    category: 'Earbud'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-45.png',
    tags: [],
    name: 'Kinera Celest Phoenixcall',
    signature: 'V-Shaped Forte',
    price: 750,
    overview: 'Uma sonoridade em V bem executada.',
    buy: 'https://s.click.aliexpress.com/e/_olyWKLx',
    review: 'https://youtu.be/CtzaLFl3uO4',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-36.png',
    tags: [],
    name: 'AKG K361',
    signature: 'Neutro-Quente',
    price: 806,
    overview: 'signature Harman.',
    buy: 'https://amzn.to/3ed7BLV',
    review: '',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-10.png',
    tags: [],
    name: 'AKG K361BT',
    signature: 'Neutro-Quente',
    price: 847,
    overview: 'Versão bluetooth do AKG K371, que é um K361 com acabamento em metal. Sem noise-cancelling.',
    buy: 'https://amzn.to/3FFBmwr',
    review: '',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-94.png',
    tags: [],
    name: 'Truthear Hexa',
    signature: 'Neutro-Frio',
    price: 851,
    overview: 'Bastante neutro, com uma abordagem mais seca.',
    buy: 'https://s.click.aliexpress.com/e/_oB2qc6h',
    review: 'https://youtu.be/pbfB8JWkxCY',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-33.png',
    tags: [],
    name: 'Kuba Disco 2',
    signature: 'Enérgico',
    price: 899,
    overview: 'Minha própria marca.',
    buy: 'https://l.kuba.audio/GwvcFt',
    review: 'https://youtu.be/6UoGqQxGems',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-34.png',
    tags: [],
    name: 'Kuba Disco 2 Pro',
    signature: 'Enérgico',
    price: 899,
    overview: 'Minha própria marca.',
    buy: 'https://l.kuba.audio/GwvcFt',
    review: 'https://youtu.be/6UoGqQxGems',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-92.png',
    tags: [],
    name: 'Letshuoer S12',
    signature: 'Enérgico',
    price: 949,
    overview: 'Enérgico do jeito certo - é tipo um KZ em esteróides.',
    buy: 'https://s.click.aliexpress.com/e/_ola3W5r',
    review: 'https://youtu.be/NvT2sZ9ivkQ',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-1.png',
    tags: ['Excelentes tecnicalidades'],
    name: 'Aful Explorer',
    signature: 'Neutro-Quente',
    price: 1168,
    overview: 'Um neutro-quente inacreditavelmente técnico: transparente, resoluto e detalhado.',
    buy: 'https://s.click.aliexpress.com/e/_olCNk1p',
    review: 'https://youtu.be/DYIIgmIN1YQ',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-35.png',
    tags: [],
    name: 'Kuba Disco Bluetooth',
    signature: 'Enérgico',
    price: 1199,
    overview: 'Minha própria marca.',
    buy: 'https://bit.ly/kuba-disco-bluetooth',
    review: 'https://youtu.be/SQTdZFNNubc',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-31.png',
    tags: [],
    name: 'Grado SR80x',
    signature: 'Seco/Direto',
    price: 1234,
    overview: 'Clássico Grado, fantástico para rock e jazz.',
    buy: 'http://Necessário%20procurar.%20Merece%20a%20busca.',
    review: '',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-32.png',
    tags: [],
    name: 'Thieaudio Ghost',
    signature: 'Neutro-Quente',
    price: 1237,
    overview: 'Sonoridade relaxada, aberta e tranquila.',
    buy: 'https://s.click.aliexpress.com/e/_Dewjetp',
    review: 'https://youtu.be/4jke__HnUkA',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-56.png',
    tags: [],
    name: 'Tri i3 MK3',
    signature: 'Natural',
    price: 1300,
    overview: 'Incrivelmente suave e agradável de ouvir.',
    buy: 'https://s.click.aliexpress.com/e/_oCCH7vZ',
    review: 'https://youtu.be/ux1crHI5xlU',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-71.png',
    tags: [],
    name: 'Nothing (Ear) 2',
    signature: 'Natural',
    price: 1343,
    overview: 'Em termos de som, meu TWS favorito.',
    buy: 'https://s.click.aliexpress.com/e/_DEHWtRZ',
    review: 'https://youtu.be/0pWt_jxzpto',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-63.png',
    tags: [],
    name: 'Etymotic ER2SE',
    signature: 'Seco/Direto',
    price: 1370,
    overview: 'Seco e direto.',
    buy: 'https://amzn.to/3GnyoTh',
    review: '',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-30.png',
    tags: [],
    name: 'Beyerdynamic DT770 Pro',
    signature: 'Neutro-Frio',
    price: 1450,
    overview: 'signature bastante natural, porém com agudos mais proeminentes.',
    buy: 'https://amzn.to/3IncGL5',
    review: '',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-95.png',
    tags: [],
    name: 'Simphonio Sunrise Dragon 2',
    signature: 'Natural',
    price: 1508,
    overview: 'Talvez o melhor earbud do mercado.',
    buy: 'https://s.click.aliexpress.com/e/_DmyvFIb',
    review: 'https://youtu.be/ENL1PZ0U62I',
    category: 'Earbud'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-9-1.png',
    tags: [],
    name: 'FiiO FT1',
    signature: 'Neutro-Quente',
    price: 1508,
    overview: 'Acerto inacreditável da FiiO. Lindo, bem construído, confortável e com uma bela sonoridade.',
    buy: 'https://s.click.aliexpress.com/e/_oEOiHBZ',
    review: 'https://youtu.be/p4fhPRsjcNo',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-57.png',
    tags: [],
    name: 'Meze Alba',
    signature: 'Natural',
    price: 1606,
    overview: 'Um Meze que briga com Chi-Fis. Som excelente, equilibrado, mas mais voltado pra abertura.',
    buy: 'https://bit.ly/3UuHYYT',
    review: 'https://youtu.be/z25XYYMZnBs',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia.png',
    tags: [],
    name: 'HyperX Cloud Orbit S',
    signature: 'Enérgico',
    price: 1669,
    overview: 'Versão da HyperX do Audeze Mobius. Fantástico.',
    buy: 'https://amzn.to/3FJQOaV',
    review: 'https://youtu.be/XJ_jclL6CPY',
    category: 'Headphone Gamer'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-112.png',
    tags: [],
    name: 'Heartfield Acoustics Deer',
    signature: 'Basshead',
    price: 1716,
    overview: 'Bem interessante pra quem quer uma boa signature basshead.',
    buy: 'https://www.linsoul.com/products/heartfield-deer',
    review: 'https://youtu.be/KEWJ17inWqA',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1.png',
    tags: [],
    name: 'Huawei Freebuds Studio',
    signature: 'Natural',
    price: 1781,
    overview: 'Ótima sonoridade, bom acabamento e funcionalidades completas.',
    buy: 'https://s.click.aliexpress.com/e/_AE6uEk',
    review: 'https://youtu.be/bEwlgWZKkdw',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-64.png',
    tags: [],
    name: 'Etymotic ER4XR',
    signature: 'Seco/Direto',
    price: 1828,
    overview: 'Seco e direto.',
    buy: 'https://amzn.to/4iBjq9M',
    review: '',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-9.png',
    tags: [],
    name: 'Sony WH-1000XM4',
    signature: 'Neutro-Quente',
    price: 1869,
    overview: 'O melhor cancelamento de ruído. Sonoridade mais ou menos.',
    buy: 'https://amzn.to/3tLrqiR',
    review: 'https://youtu.be/N0d3Fj_dj0o',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-1.png',
    tags: [],
    name: 'EPZ P50',
    signature: 'Neutro-Frio',
    price: 1902,
    overview: 'Um fone muito natural, com um tico a mais de brilho.',
    buy: 'https://s.click.aliexpress.com/e/_ooPKUq8',
    review: 'https://youtu.be/bMprpim6daM',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal2_Prancheta-1-copia-113.png',
    tags: [],
    name: 'Sennheiser HD560S',
    signature: 'Neutro-Frio',
    price: 1997,
    overview: 'Extremamente natural.',
    buy: 'https://amzn.to/3AeYctN',
    review: 'https://youtu.be/Z_k1rjVe5ZI',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-86.png',
    tags: [],
    name: '7Hz Timeless',
    signature: 'Enérgico',
    price: 2022,
    overview: 'Foi um marco pro hobby. Enérgico, vivo e sensacional.',
    buy: 'https://s.click.aliexpress.com/e/_onb5EcH',
    review: 'https://youtu.be/ycyFa9QjnxM',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-82.png',
    tags: [],
    name: 'Juzer Butterfly 61T',
    signature: 'Neutro-Quente',
    price: 2274,
    overview: 'Espetacularmente musical. Uma delícia de ouvir.',
    buy: 'https://s.click.aliexpress.com/e/_oklTz9F',
    review: 'https://youtu.be/RKFWUUavKP8',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-100.png',
    tags: [],
    name: 'Apple AirPods Pro 2',
    signature: 'Natural',
    price: 2500,
    overview: 'Um dos melhores fones do mundo. Conjunto absurdo. Som, recursos, versatilidade... tudo.',
    buy: 'https://amzn.to/3HY87JY',
    review: 'https://youtu.be/MZwJHM1mgRE',
    category: 'Intra-auricular Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-62.png',
    tags: [],
    name: '7Hz Timeless AE',
    signature: 'Neutro-Frio',
    price: 2700,
    overview: 'Versão mais refinada e polida do Timeless original.',
    buy: 'https://s.click.aliexpress.com/e/_oDIMo9B',
    review: 'https://youtu.be/aHPOBOhTdBI',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-58.png',
    tags: [],
    name: 'Dunu DaVinci',
    signature: 'Neutro-Quente',
    price: 3138,
    overview: 'O melhor na faixa de preço. Um pouco mais claro e brilhante, mas excepcionalmente limpo.',
    buy: 'https://s.click.aliexpress.com/e/_DloyXKx',
    review: 'https://youtu.be/MPmGbfs4sYI',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal2_Prancheta-1-copia-111.png',
    tags: [],
    name: 'Moondrop Para',
    signature: 'Natural',
    price: 3138,
    overview: 'Tecnicamente superior a qualquer coisa na mesma faixa de preço, porém com tuning que pode ser analítico.',
    buy: 'https://s.click.aliexpress.com/e/_DBuXmT5',
    review: 'https://youtu.be/eonH3hjOb5k',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-29.png',
    tags: ['Natural e equilibrado'],
    name: 'Sennheiser HD600',
    signature: 'Natural',
    price: 3234,
    overview: 'Referência em neutralidade.',
    buy: 'https://amzn.to/3tVAvFV',
    review: 'https://youtu.be/2CQ0jqn87HA',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-105.png',
    tags: [],
    name: 'Yanyin Canon',
    signature: 'Enérgico',
    price: 3685,
    overview: 'Absolutamente fantástico pra rock.',
    buy: 'https://s.click.aliexpress.com/e/_olLmQVn',
    review: 'https://youtu.be/perG1qVGJAA',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-52.png',
    tags: [],
    name: 'Moondrop Dusk',
    signature: 'Natural',
    price: 3795,
    overview: 'Não é barato... mas é incrível como proposta de valor. Fone natural e camaleão com o cabo DSP.',
    buy: 'https://s.click.aliexpress.com/e/_Dk5KjJV',
    review: 'https://youtu.be/xXU-t7PWm_0',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-107.png',
    tags: [],
    name: 'Moondrop Blessing 3',
    signature: 'Neutro-Frio',
    price: 3806,
    overview: 'Marco em neutralidade, ainda que seja mais diretão.',
    buy: 'https://s.click.aliexpress.com/e/_oDjRXOH',
    review: 'https://youtu.be/DI9Wq3p8TmE',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-84.png',
    tags: [],
    name: 'Aful Performer 8',
    signature: 'Musical',
    price: 3915,
    overview: 'Musical pra caramba.',
    buy: 'https://s.click.aliexpress.com/e/_opMfp9F',
    review: 'https://youtu.be/SwTiLgMsg4Y',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-83.png',
    tags: [],
    name: 'Yanyin Canon 2',
    signature: 'Neutro-Quente',
    price: 4014,
    overview: 'Como um Blon Z300, mas melhor. Belo all-rounder.',
    buy: 'https://s.click.aliexpress.com/e/_oF66quV',
    review: 'https://youtu.be/perG1qVGJAA',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-27.png',
    tags: [],
    name: 'Sivga P2 Pro',
    signature: 'Neutro-Quente',
    price: 4747,
    overview: 'Fantástico. Muito natural e musical. Excelente all-rounder.',
    buy: 'https://s.click.aliexpress.com/e/_DDwA8M1',
    review: 'https://youtu.be/2v53mzmVCEA',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-53.png',
    tags: [],
    name: 'SoftEars Studio4',
    signature: 'Natural',
    price: 4780,
    overview: 'Ultra natural e próximo da minha definição de uma neutralidade tranquila.',
    buy: 'https://s.click.aliexpress.com/e/_DlskzxF',
    review: 'https://youtu.be/Xw3x7gWfEzs',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-28.png',
    tags: [],
    name: 'Hifiman Edition XS',
    signature: 'Neutro-Frio',
    price: 4780,
    overview: 'Pegada mais fria, mas extremamente refinada. Fone claramente "high-end".',
    buy: 'https://s.click.aliexpress.com/e/_DlUQRIz',
    review: 'https://youtu.be/iQIpl2-Gxy0',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-114.png',
    tags: [],
    name: 'AudioDream Motus',
    signature: 'Basshead',
    price: 5290,
    overview: 'O ápice basshead.',
    buy: 'https://audiodream.com.br/en/produto/motus/',
    review: 'https://audiodream.com.btarget=',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/novoz_Prancheta-1-copia.png',
    tags: ['Favorito do canal', 'Graves impactantes'],
    name: 'Moondrop Meteor',
    signature: 'Natural',
    price: 5874,
    overview: 'Os melhores graves que já ouvi num IEM aliados a médios e agudos super naturais.',
    buy: 'https://s.click.aliexpress.com/e/_oog8QUd',
    review: 'https://youtu.be/UfO3ccRD93s',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-26.png',
    tags: [],
    name: 'Grado RS2x',
    signature: 'Enérgico',
    price: 5885,
    overview: 'Clássico Grado, fantástico para rock e jazz.',
    buy: 'http://Necessário%20procurar.%20Merece%20a%20busca.',
    review: 'https://youtu.be/RQPqpXbjN3Q',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-80.png',
    tags: [],
    name: 'AudioDream AD8',
    signature: 'Analítico',
    price: 5900,
    overview: 'Se você quer transparência acima de tudo.',
    buy: 'https://www.audiodream.com.br/products',
    review: 'https://youtu.be/zaR6ONrupG4',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-91.png',
    tags: [],
    name: 'Dunu SA6 MKII',
    signature: 'Musical',
    price: 6203,
    overview: 'Extremamente melodioso e gostoso de ouvir.',
    buy: 'https://s.click.aliexpress.com/e/_omVbpFr',
    review: 'https://youtu.be/Z1PncT5WTG8',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-8.png',
    tags: [],
    name: 'Apple AirPods Max',
    signature: 'Natural',
    price: 6398,
    overview: 'O melhor fone bluetooth com noise-cancelling que já testei, como conjunto.',
    buy: 'https://amzn.to/3GKHe8S',
    review: 'https://youtu.be/BFyawzZ8DOw',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-85.png',
    tags: [],
    name: 'Tanchjim Prism',
    signature: 'Seco/Direto',
    price: 6498,
    overview: 'Um fone mais direto, mas extremamente claro e encantador.',
    buy: 'https://s.click.aliexpress.com/e/_o2EXHUt',
    review: 'https://youtu.be/nskVzs7TVqA',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-87.png',
    tags: [],
    name: 'Unique Melody Mest MKII',
    signature: 'Musical',
    price: 8000,
    overview: 'Por muito tempo, foi meu IEM favorito. Muito musical.',
    buy: 'https://www.instagram.com/uniquemelodybrasil/',
    review: 'https://youtu.be/xOVePtj61PE',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-7.png',
    tags: [],
    name: 'Focal Bathys',
    signature: 'Neutro-Quente',
    price: 8000,
    overview: 'O melhor som em um fone bluetooth com noise-cancelling que já testei.',
    buy: 'https://www.audiotag.com.br',
    review: 'https://youtu.be/chXVbakXR_4',
    category: 'Headphone Bluetooth'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-7-1.png',
    tags: [],
    name: 'Stax SR-X1',
    signature: 'Natural',
    price: 8999,
    overview: 'Por incrível que pareça, um Stax custo-benefício. Som muito natural e detalhado.',
    buy: 'https://edifier.com.br/sistema-de-alto-falantes-stax-srs-x1000.html',
    review: 'https://youtu.be/j2I3x0XU1BU',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-44.png',
    tags: [],
    name: 'Sennheiser IE900',
    signature: 'V-Shaped Forte',
    price: 10600,
    overview: 'Fortemente em V, pra quem gosta. Absurdamente detalhado.',
    buy: 'https://br.octoshop.com/products/sennheiser-ie-900',
    review: 'https://youtu.be/M40Uxq2Ny8g',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-78.png',
    tags: [],
    name: 'Thieaudio Monarch MKIII',
    signature: 'Natural',
    price: 10799,
    overview: 'Natural e envolvente, como o Moonlight Ultra - porém, mais barato e sem as chaves de tuning.',
    buy: 'https://s.click.aliexpress.com/e/_DBDMWwx',
    review: 'https://youtu.be/2U-zGOVm-4c',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-90.png',
    tags: [],
    name: '64Audio U4S',
    signature: 'Enérgico',
    price: 11893,
    overview: 'Incrível pra quem quer um fone mais enérgico',
    buy: 'https://www.64audio.com/products/u4s',
    review: 'https://youtu.be/etPOvdNB46M',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-23.png',
    tags: [],
    name: 'Sennheiser HD800S',
    signature: 'Analítico',
    price: 13149,
    overview: 'Ainda um dos melhores fones do mundo. Referência em espacialidade e detalhamento.',
    buy: 'https://amzn.to/3fFOMOC',
    review: 'https://youtu.be/HB6qtvXeUro',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-79.png',
    tags: [],
    name: 'Yanyin Moonlight Ultra',
    signature: 'Natural',
    price: 14082,
    overview: 'Natural, envolvente... fenomenal.',
    buy: 'https://s.click.aliexpress.com/e/_DFI3lUL',
    review: 'https://youtu.be/pMlOtyyow18',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-76.png',
    tags: [],
    name: 'AudioDream Somnium EST',
    signature: 'Natural',
    price: 19000,
    overview: 'Diferente do MEST MKII - mais preciso, porém menos musical',
    buy: 'https://www.audiodream.com.br/products',
    review: 'https://youtu.be/d4cWBabRGbU',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-22.png',
    tags: [],
    name: 'Meze Liric 2',
    signature: 'Neutro-Frio',
    price: 21754,
    overview: 'O melhor fone fechado que já testei.',
    buy: 'https://bit.ly/meze-liric-2',
    review: 'https://youtu.be/CjoFrPK8t5g',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-4-1.png',
    tags: [],
    name: 'Meze Poet',
    signature: 'Natural',
    price: 21754,
    overview: 'Um dos meus favoritos da Meze - mais natural e envolvente que o próprio Empyrean 2.',
    buy: 'https://mezeaudio.com/products/poet?_ef_transaction_id=&amp;oid=48&amp;affid=12',
    review: 'https://youtu.be/ni0hmhuT37A',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-81.png',
    tags: [],
    name: 'Unique Melody Multiverse Mentor',
    signature: 'Neutro-Quente',
    price: 24000,
    overview: 'Junta o refinamento do MEST a uma pegada mais quente e presente.',
    buy: 'https://www.instagram.com/uniquemelodybrasil/',
    review: 'https://youtu.be/bMfFkeu66k0',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-55.png',
    tags: [],
    name: '64Audio Volür',
    signature: 'Enérgico',
    price: 27226,
    overview: 'O ápice da sonoridade energética.',
    buy: 'https://www.64audio.com/products/volur/',
    review: 'https://youtu.be/Sd3ZzgAmkSA',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-54.png',
    tags: [],
    name: 'Moondrop Solis 2',
    signature: 'Natural',
    price: 30498,
    overview: 'O melhor intra-auricular que já ouvi até hoje. Ápice da naturalidade.',
    buy: 'https://s.click.aliexpress.com/e/_oFKrOcd',
    review: 'https://youtu.be/kuhkDgt40jk',
    category: 'Intra-auricular'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-21.png',
    tags: [],
    name: 'Meze Empyrean II',
    signature: 'Natural',
    price: 32687,
    overview: 'Um fone excepcionalmente natural, ao mesmo tempo em que é musical.',
    buy: 'https://mezeaudio.com/products/empyrean2?_ef_transaction_id=&amp;oid=32&amp;affid=12',
    review: 'https://youtu.be/LnXoN_Aeeuk',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-20.png',
    tags: [],
    name: 'Stax SR-009S',
    signature: 'Analítico',
    price: 39999,
    overview: 'Transparência, detalhamento e linearidade máximos',
    buy: 'https://bit.ly/45GhbMF',
    review: 'https://youtu.be/728RMJtU2VQ',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-19.png',
    tags: [],
    name: 'Focal Utopia 2022',
    signature: 'Neutro-Quente',
    price: 40000,
    overview: 'Um HD600 elevado à máxima potência. Absurdamente natural e técnico.',
    buy: 'https://www.audiotag.com.br/produtos?q=utopia',
    review: 'https://youtu.be/lanT5yLmWgc',
    category: 'Headphone Cabeado'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-18.png',
    tags: [],
    name: 'Stax SR-X9000',
    signature: 'Neutro-Frio',
    price: 49000,
    overview: 'Ainda mais transparente e detalhado que o SR-009S, ao mesmo tempo em que é mais musical - porém, não muito.',
    buy: 'https://edifier.com.br/earspeakers-stax-sr-x9000.html',
    review: 'https://youtu.be/7du9oDkHdSA',
    category: 'Headphone Cabeado'
  }
];
