export const headphones = [
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-69.png',
    alt: 'RY4S',
    tags: [],
    name: 'RY4S',
    assinatura: 'Natural',
    price: '58,00',
    resumo: 'Um earbud incrível e muito barato.',
    buy: 'https://s.click.aliexpress.com/e/_AgoVXj',
    review: 'https://youtu.be/EpU1_q5KMFE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-3-1.png',
    alt: 'Lenovo GM2 Pro',
    tags: [],
    name: 'Lenovo GM2 Pro',
    assinatura: 'Natural',
    price: '62,00',
    resumo: 'Acho que nunca vou entender como esse fone é possível.',
    buy: 'https://s.click.aliexpress.com/e/_oF0RaMu',
    review: 'https://youtu.be/QoWY7vkh_3g'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-48.png',
    alt: 'CCA CRA',
    tags: [],
    name: 'CCA CRA',
    assinatura: 'Enérgico',
    price: '72,00',
    resumo: 'Se você quiser gastar pouco e quiser uma sonoridade viva e energética.',
    buy: 'https://s.click.aliexpress.com/e/_9wFJr7',
    review: 'https://youtu.be/KW0RU9CtPIw'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-106.png',
    alt: 'QKZ x HBB',
    tags: [],
    name: 'QKZ x HBB',
    assinatura: 'Basshead',
    price: '84,00',
    resumo: 'Pra quem quer grave pra caramba, sem gastar muito.',
    buy: 'https://s.click.aliexpress.com/e/_olZUBNF',
    review: 'https://youtu.be/Vo3-XIjqhZs'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-108.png',
    alt: 'KZ ZSN Pro',
    tags: [],
    name: 'KZ ZSN Pro',
    assinatura: 'V-Shaped Forte',
    price: '101,00',
    resumo: 'Enérgico pra caramba, custando pouco.',
    buy: 'https://s.click.aliexpress.com/e/_oCdLq5J',
    review: 'https://youtu.be/S9Jo-znQrnk'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-41.png',
    alt: 'Redmi Buds 6 Active',
    tags: [],
    name: 'Redmi Buds 6 Active',
    assinatura: 'Natural',
    price: '110,00',
    resumo: 'Se você não se incomodar com o volume mais baixo, até melhor que o QCY T20.',
    buy: 'https://s.click.aliexpress.com/e/_DD9W2Fr',
    review: 'https://youtu.be/AJSEmxiIp4g'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-47.png',
    alt: 'Moondrop Chu II',
    tags: ['Favorito do canal'],
    name: 'Moondrop Chu II',
    assinatura: 'Natural',
    price: '132,00',
    resumo: 'O melhor in-ear em torno de R$100.',
    buy: 'https://s.click.aliexpress.com/e/_DD7BdAT',
    review: 'https://youtu.be/tgcV8NZS3ho'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-73.png',
    alt: 'QCY T20',
    tags: [],
    name: 'QCY T20',
    assinatura: 'Natural',
    price: '146,00',
    resumo: 'Um excelente TWS em formato de earbud.',
    buy: 'https://s.click.aliexpress.com/e/_DdoXtRd',
    review: 'https://youtu.be/OhOwMV5yTxA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-6-1.png',
    alt: 'Kawano AudioHoraiko',
    tags: [],
    name: 'Kawano Audio Horaiko',
    assinatura: 'Neutro-Quente',
    price: '150,00',
    resumo: 'Projeto artesanal, feito no Brasil. Sensacional!',
    buy: 'https://www.kawanoaudio.com',
    review: 'https://youtu.be/WBGbNFZNPvE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-16.png',
    alt: 'Havit H630BT',
    tags: [],
    name: 'Havit H630BT',
    assinatura: 'Natural',
    price: '158,00',
    resumo: 'Um fone bluetooth extremamente acessível, com sonoridade legal. E tem rádio!',
    buy: 'https://youtu.be/HuNNC9B6S0Y',
    review: 'https://s.zbanx.com/r/1G7fQ37Ye25E'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-2-1.png',
    alt: 'QCY T13 ANC',
    tags: [],
    name: 'QCY T13 ANC',
    assinatura: 'Natural',
    price: '165,00',
    resumo: 'Um belo sucessor do incrível T13 ANC. Relação custo-benefício inacreditável.',
    buy: 'https://s.click.aliexpress.com/e/_oDD7t5O',
    review: 'https://youtu.be/fWOAdu48rtw'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-17.png',
    alt: 'Arcano AR-414B',
    tags: [],
    name: 'Arcano AR-414B',
    assinatura: 'Neutro-Quente',
    price: '170,00',
    resumo: 'Envolvente e muito competente para um fone bluetooth tão barato (use o cupom MINDTHEHEADPHONE).',
    buy: 'https://www.lojadiscovery.com.br/ar-414b',
    review: 'https://youtu.be/B1GwNqSl62w'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-61.png',
    alt: 'Anker Soundcore P20i',
    tags: [],
    name: 'Anker Soundcore P20i',
    assinatura: 'Enérgico',
    price: '182,00',
    resumo: 'Consideravelmente mais divertido e alto que o Space Travel, porém menos natural.',
    buy: 'https://s.zbanx.com/r/QzIHFpvaxEKB',
    review: 'https://youtu.be/eslfbd_DepM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-88.png',
    alt: 'Moondrop Chu',
    tags: [],
    name: 'Moondrop Chu',
    assinatura: 'Neutro-Frio',
    price: '190,00',
    resumo: 'Mais frio que o Chu 2, mas ainda excepcionalmente natural.',
    buy: 'https://s.click.aliexpress.com/e/_oBPtIhR',
    review: 'https://youtu.be/XXncYp0M0NU'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-5.png',
    alt: 'Havit Fuxi-H3',
    tags: [],
    name: 'Havit Fuxi-H3',
    assinatura: 'Natural',
    price: '193,00',
    resumo: 'Muitas opções de conectividade. Pode ser bem interessante pra jogos por conta disso.',
    buy: 'https://s.zbanx.com/r/7YDkD33Cs90e%20%20%20%20',
    review: 'https://youtu.be/HuNNC9B6S0Y'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-42.png',
    alt: 'Huawei Freebuds 2SE',
    tags: [],
    name: 'Huawei Freebuds 2SE',
    assinatura: 'Enérgico',
    price: '199,00',
    resumo: 'Uma opção mais equilibrada ao QCY T20, que é mais cheio.',
    buy: 'https://s.zbanx.com/r/4jHv5K88a66w',
    review: 'https://youtu.be/o-4htA1U2LM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-68.png',
    alt: 'QCY HT10',
    tags: [],
    name: 'QCY HT10',
    assinatura: 'Natural',
    price: '199,00',
    resumo: 'Médios bem melhores que o T20, graves e agudos melhores que o Freebuds 2SE',
    buy: 'https://amzn.to/3SRORmn',
    review: 'https://youtu.be/1EGGBnM_7FM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-6.png',
    alt: 'Havit H2002D',
    tags: [],
    name: 'Havit H2002D',
    assinatura: 'Natural',
    price: '199,00',
    resumo: 'Sonoridade mais quente, surpreendentemente boa para um fone nessa faixa de preço.',
    buy: 'https://s.zbanx.com/r/JC3c5NPl065Q',
    review: 'https://youtu.be/HuNNC9B6S0Y'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-98.png',
    alt: 'Moondrop SpaceTravel',
    tags: [],
    name: 'Moondrop Space Travel',
    assinatura: 'Natural',
    price: '207,00',
    resumo: 'Não é a maior bateria da categoria, mas é o melhor som.',
    buy: 'https://s.click.aliexpress.com/e/_DEfaQRV',
    review: 'https://youtu.be/UYwz7aItYuQ'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-103.png',
    alt: 'OneOdio Pro-10',
    tags: [],
    name: 'OneOdio Pro-10',
    assinatura: 'Neutro-Quente',
    price: '207,00',
    resumo: 'Headphone barato muito competente, apesar dos graves fortes demais.',
    buy: 'https://s.click.aliexpress.com/e/_A5LlPK',
    review: 'https://youtu.be/Sjv257nTm4M'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-75.png',
    alt: 'Tin Hifi C2 MechWarrior',
    tags: [],
    name: 'Tin Hifi C2 Mech Warrior',
    assinatura: 'Natural',
    price: '215,00',
    resumo: 'Uma opção mais eufônica ao ZS10 Pro X',
    buy: 'https://s.click.aliexpress.com/e/_DEmpPfj',
    review: 'https://youtu.be/s6NbmtO905I'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-104.png',
    alt: 'Arcano SHP80',
    tags: [],
    name: 'Arcano SHP80',
    assinatura: 'Neutro-Frio',
    price: '235,00',
    resumo: 'Confortável e com sonoridade aberta e arejada (use o cupom MINDTHEHEADPHONE).',
    buy: 'https://www.lojadiscovery.com.br/arc-shp80',
    review: 'https://youtu.be/08sU1AYHX8s'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-5-1.png',
    alt: 'Kawano Audio Hanabi',
    tags: [],
    name: 'Kawano Audio Hanabi',
    assinatura: 'Neutro-Quente',
    price: '250,00',
    resumo: 'Projeto artesanal, feito no Brasil. Sensacional!',
    buy: 'https://www.kawanoaudio.com',
    review: 'https://youtu.be/WBGbNFZNPvE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-89.png',
    alt: 'Blon Z300',
    tags: [],
    name: 'Blon Z300',
    assinatura: 'Neutro-Quente',
    price: '256,00',
    resumo: 'Caloroso do jeito certo. Fantástico pra gêneros mais pesados.',
    buy: 'https://s.click.aliexpress.com/e/_oEU4PfR',
    review: 'https://youtu.be/yXIVWHolcho'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-97.png',
    alt: 'QCY MeloBuds Pro',
    tags: [],
    name: 'QCY MeloBuds Pro',
    assinatura: 'Natural',
    price: '262,00',
    resumo: 'Belíssimo conjunto pelo preço, com som bem envolvente.',
    buy: 'https://s.click.aliexpress.com/e/_DmGiIQN',
    review: 'https://youtu.be/G72tDT2FqTc'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-67.png',
    alt: 'Arcano SHP300',
    tags: [],
    name: 'Arcano SHP300',
    assinatura: 'Neutro-Quente',
    price: '280,00',
    resumo: 'Sonoridade viva e energética (use o cupom MINDTHEHEADPHONE).',
    buy: 'https://www.lojadiscovery.com.br/arc-shp300',
    review: 'https://youtu.be/2uIE9rXdfYI'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-46.png',
    alt: 'KZ ZS10 Pro X',
    tags: [],
    name: 'KZ ZS10 Pro X',
    assinatura: 'Enérgico',
    price: '289,00',
    resumo: 'Finalmente, a KZ de volta no jogo. A incrível releitura de um fone lendário. Excepcional.',
    buy: 'https://s.click.aliexpress.com/e/_DCEASFV',
    review: 'https://youtu.be/F8SRRMTV1vY'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-15.png',
    alt: 'Havit H655BT',
    tags: [],
    name: 'Havit H655BT',
    assinatura: 'Natural',
    price: '299,00',
    resumo: 'Boa opção pra quem quer um fone bluetooth com cancelamento de ruídos super barato.',
    buy: 'https://mercadolivre.com/sec/1nAZwaE',
    review: 'https://youtu.be/qZKF7c7IJzk'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-93.png',
    alt: 'Tin Hifi T2',
    tags: [],
    name: 'Tin Hifi T2',
    assinatura: 'Neutro-Frio',
    price: '306,00',
    resumo: 'Um dos grandes marcos do movimento chi-fi. Incrivelmente delicado e envolvente.',
    buy: 'https://s.click.aliexpress.com/e/_oke9qzB',
    review: 'https://youtu.be/JkBxCTrqeWY'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-110.png',
    alt: 'KZ ZAR',
    tags: [],
    name: 'KZ ZAR',
    assinatura: 'Basshead',
    price: '375,00',
    resumo: 'Um belo basshead da KZ.',
    buy: 'https://s.click.aliexpress.com/e/_opsqCnF',
    review: 'https://youtu.be/ai-ecH6i5s8'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-14.png',
    alt: 'Edifier W800BT Plus',
    tags: [],
    name: 'Edifier W800BT Plus',
    assinatura: 'Natural',
    price: '399,00',
    resumo: 'Fone equilibrado e competente.',
    buy: 'https://amzn.to/3saRIvY',
    review: 'https://youtu.be/bkgr2ND_zPM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-13.png',
    alt: 'Edifier W820NB',
    tags: [],
    name: 'Edifier W820NB',
    assinatura: 'Natural',
    price: '399,00',
    resumo: 'Incrível pelo que custa. Sonoridade equilibrada e interessante.',
    buy: 'https://amzn.to/3Q3LpCJ',
    review: 'https://youtu.be/ehJTwlmTfzU'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-74.png',
    alt: 'Armer SH450',
    tags: [],
    name: 'Armer SH450',
    assinatura: 'Neutro-Quente',
    price: '400,00',
    resumo: 'Intenso porém equilibrado. Pegada mais fechada.',
    buy: 'https://amzn.to/42VcNY44',
    review: 'https://youtu.be/1g5FgBkeBlY'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-96.png',
    alt: 'KZ Xtra',
    tags: [],
    name: 'KZ Xtra',
    assinatura: 'Neutro-Frio',
    price: '403,00',
    resumo: 'Um dos TWS que menos soa como um TWS. Fantástico, com som mais aberto e transparente.',
    buy: 'https://s.click.aliexpress.com/e/_DFjDYRR',
    review: 'https://youtu.be/Bo6SCuzoAaQ'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-99.png',
    alt: 'Redmi Buds 5 Pro',
    tags: [],
    name: 'Redmi Buds 5 Pro',
    assinatura: 'Natural',
    price: '404,00',
    resumo: 'Alternativa com mais recursos ao KZ Xtra, porém com som tecnicamente inferior',
    buy: 'https://s.click.aliexpress.com/e/_DcQHny9',
    review: 'https://youtu.be/AJSEmxiIp4g'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-12.png',
    alt: 'Haylou S30 Pro',
    tags: [],
    name: 'Haylou S30 Pro',
    assinatura: 'Natural',
    price: '427,00',
    resumo: 'Bela opção para home-office, com o microfone destacável.',
    buy: 'https://s.click.aliexpress.com/e/_DElyeHZ',
    review: 'https://youtu.be/richJiDWQcU'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-66.png',
    alt: 'Samsung Galaxy BudsLive',
    tags: [],
    name: 'Samsung Galaxy Buds Live',
    assinatura: 'Neutro-Quente',
    price: '449,00',
    resumo: 'Ainda muito bom, porém fora de produção.',
    buy: 'https://amzn.to/3MGyNhK',
    review: 'https://youtu.be/BYfCV-bQv6w'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-4.png',
    alt: 'Pichau P852 Atria',
    tags: [],
    name: 'Pichau P852 Atria',
    assinatura: 'Natural',
    price: '450,00',
    resumo: 'Boa opção de headset acessível com desempenho competente.',
    buy: 'https://bit.ly/3MkBPIg',
    review: 'https://youtu.be/buL8jbMxFyo'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-60.png',
    alt: 'Anker X10',
    tags: [],
    name: 'Anker X10',
    assinatura: 'Natural',
    price: '490,00',
    resumo: 'Requer equalização pra ficar legal, mas é ótimo para exercícios pelo design e resistência.',
    buy: 'https://s.click.aliexpress.com/e/_DEEWEyJ',
    review: 'https://youtu.be/eslfbd_DepM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-109.png',
    alt: 'Truthear Zero',
    tags: [],
    name: 'Truthear Zero',
    assinatura: 'Basshead',
    price: '523,00',
    resumo: 'Sonoridade em tese Harman, mas me parece bem gravudo.',
    buy: 'https://s.click.aliexpress.com/e/_oDAqbJn',
    review: 'https://youtu.be/8JBKJPWboWo'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-2.png',
    alt: 'HyperX Cloud Core',
    tags: [],
    name: 'HyperX Cloud Core',
    assinatura: 'Natural',
    price: '539,00',
    resumo: 'Um clássico headset.',
    buy: 'https://amzn.to/328j9tH',
    review: 'http://-'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-3.png',
    alt: 'Pichau P852 Vega',
    tags: [],
    name: 'Pichau P852 Vega',
    assinatura: 'Natural',
    price: '550,00',
    resumo: 'Quase igual ao Atria, porém USB, com equalizador e um efeito surround sutil e interessante.',
    buy: 'https://bit.ly/35RAXv5',
    review: 'https://youtu.be/buL8jbMxFyo'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-65.png',
    alt: 'Anker Soundcore SpaceA40',
    tags: [],
    name: 'Anker Soundcore Space A40',
    assinatura: 'Neutro-Frio',
    price: '555,00',
    resumo: 'Personalidade mais espacial e eufônica.',
    buy: 'https://s.zbanx.com/r/uMDDYDUwu4gN',
    review: 'https://youtu.be/eslfbd_DepM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-50.png',
    alt: 'Truthear Zero:RED',
    tags: ['Favorito do canal'],
    name: 'Truthear Zero:RED',
    assinatura: 'Natural',
    price: '566,00',
    resumo: 'Absolutamente incrível. Para os meus ouvidos, melhor até que o Hexa.',
    buy: 'https://s.click.aliexpress.com/e/_DdwwTgZ',
    review: 'https://youtu.be/8JBKJPWboWo'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-8-1.png',
    alt: 'Anker SoundcoreLiberty 4NC',
    tags: [],
    name: 'Anker Soundcore Liberty 4NC',
    assinatura: 'Natural',
    price: '566,00',
    resumo: 'Conjunto excepcional pelo que custa: construção, recursos, som e conforto.',
    buy: 'https://s.click.aliexpress.com/e/_omQqKWG',
    review: 'https://youtu.be/Yvfwc-KJD-s'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-51.png',
    alt: 'Moondrop May',
    tags: [],
    name: 'Moondrop May',
    assinatura: 'Natural',
    price: '577,00',
    resumo: 'Muito natural, com os recursos do cabo DSP.',
    buy: 'https://s.click.aliexpress.com/e/_DlWwVVN',
    review: 'https://youtu.be/ZXlejDD-toA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-10-1.png',
    alt: 'FiiO JT1',
    tags: [],
    name: 'FiiO JT1',
    assinatura: 'Neutro-Quente',
    price: '577,00',
    resumo: 'Uma alternativa mais musical e eufônica ao Hifiman HE400SE.',
    buy: 'https://s.click.aliexpress.com/e/_DnFOj1R',
    review: 'https://youtu.be/XO6nbeduc2o'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-70.png',
    alt: 'Philips SHP9500',
    tags: [],
    name: 'Philips SHP9500',
    assinatura: 'Analítico',
    price: '591,00',
    resumo: 'Muito detalhado, porém com pouco grave.',
    buy: 'https://s.click.aliexpress.com/e/_AW1L4F',
    review: 'https://youtu.be/duTiBYfhLZQ'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-43.png',
    alt: 'Huawei Freebuds 6i',
    tags: [],
    name: 'Huawei Freebuds 6i',
    assinatura: 'Natural',
    price: '599,00',
    resumo: 'Um dos melhores cancelamentos ativos de ruídos pelo preço.',
    buy: 'https://amzn.to/4fz38wS',
    review: 'https://youtu.be/b1tjbmkjvKA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-38.png',
    alt: 'Kuba Nia Lite',
    tags: [],
    name: 'Kuba Nia Lite',
    assinatura: 'Enérgico',
    price: '599,00',
    resumo: 'Minha própria marca.',
    buy: 'https://kuba.audio/products/nia?variant=49525569225019',
    review: 'https://youtu.be/CUE_Cy5gaaE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-11.png',
    alt: 'Anker Soundcore Q30',
    tags: [],
    name: 'Anker Soundcore Q30',
    assinatura: 'Basshead',
    price: '612,00',
    resumo: 'Semelhante ao W820NB, porém com melhor construção. Requer equalização.',
    buy: 'https://s.click.aliexpress.com/e/_AAN4nF',
    review: 'https://youtu.be/KPn8sV8bf4c'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-40.png',
    alt: 'Huawei Freebuds 5',
    tags: [],
    name: 'Huawei Freebuds 5',
    assinatura: 'Natural',
    price: '649,00',
    resumo: 'Envolvente e divertido. Excelente pelo preço.',
    buy: 'https://amzn.to/3Fm0XNe',
    review: 'https://youtu.be/I9oflmOAJRU'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-37.png',
    alt: 'Kuba Nia Headset',
    tags: [],
    name: 'Kuba Nia Headset',
    assinatura: 'Enérgico',
    price: '649,00',
    resumo: 'Minha própria marca.',
    buy: 'https://kuba.audio/products/nia?variant=49525569225019',
    review: 'https://youtu.be/CUE_Cy5gaaE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-39.png',
    alt: 'Hifiman HE400SE',
    tags: [],
    name: 'Hifiman HE400SE',
    assinatura: 'Seco/Direto',
    price: '666,00',
    resumo: 'Um fantástico planar de entrada e uma verdadeira barganha.',
    buy: 'https://s.click.aliexpress.com/e/_A5cSPA',
    review: 'https://youtu.be/hQHY2pngXHA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-101.png',
    alt: 'Samsung Galaxy Buds2Pro',
    tags: [],
    name: 'Samsung Galaxy Buds2 Pro',
    assinatura: 'Natural',
    price: '698,00',
    resumo: 'Sonoridade Harman e uma bela relação custo-benefício.',
    buy: 'https://amzn.to/3YxkbZC',
    review: 'https://youtu.be/SYgYoC6b9Mk'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-72.png',
    alt: 'Armer SH550',
    tags: [],
    name: 'Armer SH550',
    assinatura: 'Neutro-Frio',
    price: '699,00',
    resumo: 'Intenso porém equilibrado. Pegada mais aberta.',
    buy: 'https://amzn.to/3NMo0G2',
    review: 'https://youtu.be/1g5FgBkeBlY'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-102.png',
    alt: 'Dunu Alpha 3',
    tags: [],
    name: 'Dunu Alpha 3',
    assinatura: 'Natural',
    price: '741,00',
    resumo: 'Melhor que o RY4S em linearidade e transparência, porém muito mais caro.',
    buy: 'https://s.click.aliexpress.com/e/_DE365nd',
    review: 'https://youtu.be/ENL1PZ0U62I'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-45.png',
    alt: 'Kinera CelestPhoenixcall',
    tags: [],
    name: 'Kinera Celest Phoenixcall',
    assinatura: 'V-Shaped Forte',
    price: '750,00',
    resumo: 'Uma sonoridade em V bem executada.',
    buy: 'https://s.click.aliexpress.com/e/_olyWKLx',
    review: 'https://youtu.be/CtzaLFl3uO4'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-36.png',
    alt: 'AKG K361',
    tags: [],
    name: 'AKG K361',
    assinatura: 'Neutro-Quente',
    price: '806,00',
    resumo: 'Assinatura Harman.',
    buy: 'https://amzn.to/3ed7BLV',
    review: 'http://-'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-10.png',
    alt: 'AKG K361BT',
    tags: [],
    name: 'AKG K361BT',
    assinatura: 'Neutro-Quente',
    price: '847,00',
    resumo: 'Versão bluetooth do AKG K371, que é um K361 com acabamento em metal. Sem noise-cancelling.',
    buy: 'https://amzn.to/3FFBmwr',
    review: 'http://-'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-94.png',
    alt: 'Truthear Hexa',
    tags: [],
    name: 'Truthear Hexa',
    assinatura: 'Neutro-Frio',
    price: '851,00',
    resumo: 'Bastante neutro, com uma abordagem mais seca.',
    buy: 'https://s.click.aliexpress.com/e/_oB2qc6h',
    review: 'https://youtu.be/pbfB8JWkxCY'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-33.png',
    alt: 'Kuba Disco 2',
    tags: [],
    name: 'Kuba Disco 2',
    assinatura: 'Enérgico',
    price: '899,00',
    resumo: 'Minha própria marca.',
    buy: 'https://l.kuba.audio/GwvcFt',
    review: 'https://youtu.be/6UoGqQxGems'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-34.png',
    alt: 'Kuba Disco 2 Pro',
    tags: [],
    name: 'Kuba Disco 2 Pro',
    assinatura: 'Enérgico',
    price: '899,00',
    resumo: 'Minha própria marca.',
    buy: 'https://l.kuba.audio/GwvcFt',
    review: 'https://youtu.be/6UoGqQxGems'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-92.png',
    alt: 'Letshuoer S12',
    tags: [],
    name: 'Letshuoer S12',
    assinatura: 'Enérgico',
    price: '949,00',
    resumo: 'Enérgico do jeito certo - é tipo um KZ em esteróides.',
    buy: 'https://s.click.aliexpress.com/e/_ola3W5r',
    review: 'https://youtu.be/NvT2sZ9ivkQ'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-1.png',
    alt: 'Aful Explorer',
    tags: ['Excelentes tecnicalidades'],
    name: 'Aful Explorer',
    assinatura: 'Neutro-Quente',
    price: '1.168,00',
    resumo: 'Um neutro-quente inacreditavelmente técnico: transparente, resoluto e detalhado.',
    buy: 'https://s.click.aliexpress.com/e/_olCNk1p',
    review: 'https://youtu.be/DYIIgmIN1YQ'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-35.png',
    alt: 'Kuba Disco Bluetooth',
    tags: [],
    name: 'Kuba Disco Bluetooth',
    assinatura: 'Enérgico',
    price: '1.199,00',
    resumo: 'Minha própria marca.',
    buy: 'https://bit.ly/kuba-disco-bluetooth',
    review: 'https://youtu.be/SQTdZFNNubc'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-31.png',
    alt: 'Grado SR80x',
    tags: [],
    name: 'Grado SR80x',
    assinatura: 'Seco/Direto',
    price: '1.234,00',
    resumo: 'Clássico Grado, fantástico para rock e jazz.',
    buy: 'http://Necessário%20procurar.%20Merece%20a%20busca.',
    review: 'http://-'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-32.png',
    alt: 'Thieaudio Ghost',
    tags: [],
    name: 'Thieaudio Ghost',
    assinatura: 'Neutro-Quente',
    price: '1.237,00',
    resumo: 'Sonoridade relaxada, aberta e tranquila.',
    buy: 'https://s.click.aliexpress.com/e/_Dewjetp',
    review: 'https://youtu.be/4jke__HnUkA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-56.png',
    alt: 'Tri i3 MK3',
    tags: [],
    name: 'Tri i3 MK3',
    assinatura: 'Natural',
    price: '1.300,00',
    resumo: 'Incrivelmente suave e agradável de ouvir.',
    buy: 'https://s.click.aliexpress.com/e/_oCCH7vZ',
    review: 'https://youtu.be/ux1crHI5xlU'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-71.png',
    alt: 'Nothing (Ear) 2',
    tags: [],
    name: 'Nothing (Ear) 2',
    assinatura: 'Natural',
    price: '1.343,00',
    resumo: 'Em termos de som, meu TWS favorito.',
    buy: 'https://s.click.aliexpress.com/e/_DEHWtRZ',
    review: 'https://youtu.be/0pWt_jxzpto'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-63.png',
    alt: 'Etymotic ER2SE',
    tags: [],
    name: 'Etymotic ER2SE',
    assinatura: 'Seco/Direto',
    price: '1.370,00',
    resumo: 'Seco e direto.',
    buy: 'https://amzn.to/3GnyoTh'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-30.png',
    alt: 'Beyerdynamic DT770Pro',
    tags: [],
    name: 'Beyerdynamic DT770 Pro',
    assinatura: 'Neutro-Frio',
    price: '1.450,00',
    resumo: 'Assinatura bastante natural, porém com agudos mais proeminentes.',
    buy: 'https://amzn.to/3IncGL5',
    review: 'http://-'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-95.png',
    alt: 'Simphonio SunriseDragon 2',
    tags: [],
    name: 'Simphonio Sunrise Dragon 2',
    assinatura: 'Natural',
    price: '1.508,00',
    resumo: 'Talvez o melhor earbud do mercado.',
    buy: 'https://s.click.aliexpress.com/e/_DmyvFIb',
    review: 'https://youtu.be/ENL1PZ0U62I'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-9-1.png',
    alt: 'FiiO FT1',
    tags: [],
    name: 'FiiO FT1',
    assinatura: 'Neutro-Quente',
    price: '1.508,00',
    resumo: 'Acerto inacreditável da FiiO. Lindo, bem construído, confortável e com uma bela sonoridade.',
    buy: 'https://s.click.aliexpress.com/e/_oEOiHBZ',
    review: 'https://youtu.be/p4fhPRsjcNo'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-57.png',
    alt: 'Meze Alba',
    tags: [],
    name: 'Meze Alba',
    assinatura: 'Natural',
    price: '1.606,00',
    resumo: 'Um Meze que briga com Chi-Fis. Som excelente, equilibrado, mas mais voltado pra abertura.',
    buy: 'https://bit.ly/3UuHYYT',
    review: 'https://youtu.be/z25XYYMZnBs'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia.png',
    alt: 'HyperX Cloud Orbit S',
    tags: [],
    name: 'HyperX Cloud Orbit S',
    assinatura: 'Enérgico',
    price: '1.669,00',
    resumo: 'Versão da HyperX do Audeze Mobius. Fantástico.',
    buy: 'https://amzn.to/3FJQOaV',
    review: 'https://youtu.be/XJ_jclL6CPY'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-112.png',
    alt: 'Heartfield AcousticsDeer',
    tags: [],
    name: 'Heartfield Acoustics Deer',
    assinatura: 'Basshead',
    price: '1.716,00',
    resumo: 'Bem interessante pra quem quer uma boa assinatura basshead.',
    buy: 'https://www.linsoul.com/products/heartfield-deer',
    review: 'https://youtu.be/KEWJ17inWqA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1.png',
    alt: 'Huawei Freebuds Studio',
    tags: [],
    name: 'Huawei Freebuds Studio',
    assinatura: 'Natural',
    price: '1.781,00',
    resumo: 'Ótima sonoridade, bom acabamento e funcionalidades completas.',
    buy: 'https://s.click.aliexpress.com/e/_AE6uEk',
    review: 'https://youtu.be/bEwlgWZKkdw'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-64.png',
    alt: 'Etymotic ER4XR',
    tags: [],
    name: 'Etymotic ER4XR',
    assinatura: 'Seco/Direto',
    price: '1.828,00',
    resumo: 'Seco e direto.',
    buy: 'https://amzn.to/4iBjq9M'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-9.png',
    alt: 'Sony WH-1000XM4',
    tags: [],
    name: 'Sony WH-1000XM4',
    assinatura: 'Neutro-Quente',
    price: '1.869,00',
    resumo: 'O melhor cancelamento de ruído. Sonoridade mais ou menos.',
    buy: 'https://amzn.to/3tLrqiR',
    review: 'https://youtu.be/N0d3Fj_dj0o'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-1.png',
    alt: 'EPZ P50',
    tags: [],
    name: 'EPZ P50',
    assinatura: 'Neutro-Frio',
    price: '1.902,00',
    resumo: 'Um fone muito natural, com um tico a mais de brilho.',
    buy: 'https://s.click.aliexpress.com/e/_ooPKUq8',
    review: 'https://youtu.be/bMprpim6daM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal2_Prancheta-1-copia-113.png',
    alt: 'Sennheiser HD560S',
    tags: [],
    name: 'Sennheiser HD560S',
    assinatura: 'Neutro-Frio',
    price: '1.997,00',
    resumo: 'Extremamente natural.',
    buy: 'https://amzn.to/3AeYctN',
    review: 'https://youtu.be/Z_k1rjVe5ZI'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-86.png',
    alt: '7Hz Timeless',
    tags: [],
    name: '7Hz Timeless',
    assinatura: 'Enérgico',
    price: '2.022,00',
    resumo: 'Foi um marco pro hobby. Enérgico, vivo e sensacional.',
    buy: 'https://s.click.aliexpress.com/e/_onb5EcH',
    review: 'https://youtu.be/ycyFa9QjnxM'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-82.png',
    alt: 'Juzer Butterfly 61T',
    tags: [],
    name: 'Juzer Butterfly 61T',
    assinatura: 'Neutro-Quente',
    price: '2.274,00',
    resumo: 'Espetacularmente musical. Uma delícia de ouvir.',
    buy: 'https://s.click.aliexpress.com/e/_oklTz9F',
    review: 'https://youtu.be/RKFWUUavKP8'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-100.png',
    alt: 'Apple AirPods Pro 2',
    tags: [],
    name: 'Apple AirPods Pro 2',
    assinatura: 'Natural',
    price: '2.500,00',
    resumo: 'Um dos melhores fones do mundo. Conjunto absurdo. Som, recursos, versatilidade... tudo.',
    buy: 'https://amzn.to/3HY87JY',
    review: 'https://youtu.be/MZwJHM1mgRE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-62.png',
    alt: '7Hz Timeless AE',
    tags: [],
    name: '7Hz Timeless AE',
    assinatura: 'Neutro-Frio',
    price: '2.700,00',
    resumo: 'Versão mais refinada e polida do Timeless original.',
    buy: 'https://s.click.aliexpress.com/e/_oDIMo9B',
    review: 'https://youtu.be/aHPOBOhTdBI'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-58.png',
    alt: 'Dunu DaVinci',
    tags: [],
    name: 'Dunu DaVinci',
    assinatura: 'Neutro-Quente',
    price: '3.138,00',
    resumo: 'O melhor na faixa de preço. Um pouco mais claro e brilhante, mas excepcionalmente limpo.',
    buy: 'https://s.click.aliexpress.com/e/_DloyXKx',
    review: 'https://youtu.be/MPmGbfs4sYI'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal2_Prancheta-1-copia-111.png',
    alt: 'Moondrop Para',
    tags: [],
    name: 'Moondrop Para',
    assinatura: 'Natural',
    price: '3.138,00',
    resumo: 'Tecnicamente superior a qualquer coisa na mesma faixa de preço, porém com tuning que pode ser analítico.',
    buy: 'https://s.click.aliexpress.com/e/_DBuXmT5',
    review: 'https://youtu.be/eonH3hjOb5k'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-29.png',
    alt: 'Sennheiser HD600',
    tags: ['Natural e equilibrado'],
    name: 'Sennheiser HD600',
    assinatura: 'Natural',
    price: '3.234,00',
    resumo: 'Referência em neutralidade.',
    buy: 'https://amzn.to/3tVAvFV',
    review: 'https://youtu.be/2CQ0jqn87HA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-105.png',
    alt: 'Yanyin Canon',
    tags: [],
    name: 'Yanyin Canon',
    assinatura: 'Enérgico',
    price: '3.685,00',
    resumo: 'Absolutamente fantástico pra rock.',
    buy: 'https://s.click.aliexpress.com/e/_olLmQVn',
    review: 'https://youtu.be/perG1qVGJAA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-52.png',
    alt: 'Moondrop Dusk',
    tags: [],
    name: 'Moondrop Dusk',
    assinatura: 'Natural',
    price: '3.795,00',
    resumo: 'Não é barato... mas é incrível como proposta de valor. Fone natural e camaleão com o cabo DSP.',
    buy: 'https://s.click.aliexpress.com/e/_Dk5KjJV',
    review: 'https://youtu.be/xXU-t7PWm_0'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-107.png',
    alt: 'Moondrop Blessing 3',
    tags: [],
    name: 'Moondrop Blessing 3',
    assinatura: 'Neutro-Frio',
    price: '3.806,00',
    resumo: 'Marco em neutralidade, ainda que seja mais diretão.',
    buy: 'https://s.click.aliexpress.com/e/_oDjRXOH',
    review: 'https://youtu.be/DI9Wq3p8TmE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-84.png',
    alt: 'Aful Performer 8',
    tags: [],
    name: 'Aful Performer 8',
    assinatura: 'Musical',
    price: '3.915,00',
    resumo: 'Musical pra caramba.',
    buy: 'https://s.click.aliexpress.com/e/_opMfp9F',
    review: 'https://youtu.be/SwTiLgMsg4Y'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-83.png',
    alt: 'Yanyin Canon 2',
    tags: [],
    name: 'Yanyin Canon 2',
    assinatura: 'Neutro-Quente',
    price: '4.014,00',
    resumo: 'Como um Blon Z300, mas melhor. Belo all-rounder.',
    buy: 'https://s.click.aliexpress.com/e/_oF66quV',
    review: 'https://youtu.be/perG1qVGJAA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-27.png',
    alt: 'Sivga P2 Pro',
    tags: [],
    name: 'Sivga P2 Pro',
    assinatura: 'Neutro-Quente',
    price: '4.747,00',
    resumo: 'Fantástico. Muito natural e musical. Excelente all-rounder.',
    buy: 'https://s.click.aliexpress.com/e/_DDwA8M1',
    review: 'https://youtu.be/2v53mzmVCEA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-53.png',
    alt: 'SoftEars Studio4',
    tags: [],
    name: 'SoftEars Studio4',
    assinatura: 'Natural',
    price: '4.780,00',
    resumo: 'Ultra natural e próximo da minha definição de uma neutralidade tranquila.',
    buy: 'https://s.click.aliexpress.com/e/_DlskzxF',
    review: 'https://youtu.be/Xw3x7gWfEzs'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-28.png',
    alt: 'Hifiman Edition XS',
    tags: [],
    name: 'Hifiman Edition XS',
    assinatura: 'Neutro-Frio',
    price: '4.780,00',
    resumo: 'Pegada mais fria, mas extremamente refinada. Fone claramente "high-end".',
    buy: 'https://s.click.aliexpress.com/e/_DlUQRIz',
    review: 'https://youtu.be/iQIpl2-Gxy0'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-114.png',
    alt: 'AudioDream Motus',
    tags: [],
    name: 'AudioDream Motus',
    assinatura: 'Basshead',
    price: '5.290,00',
    resumo: 'O ápice basshead.',
    buy: 'https://audiodream.com.br/en/produto/motus/',
    review: 'https://audiodream.com.btarget='
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/novoz_Prancheta-1-copia.png',
    alt: 'Moondrop Meteor',
    tags: ['Favorito do canal', 'Graves impactantes'],
    name: 'Moondrop Meteor',
    assinatura: 'Natural',
    price: '5.874,00',
    resumo: 'Os melhores graves que já ouvi num IEM aliados a médios e agudos super naturais.',
    buy: 'https://s.click.aliexpress.com/e/_oog8QUd',
    review: 'https://youtu.be/UfO3ccRD93s'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-26.png',
    alt: 'Grado RS2x',
    tags: [],
    name: 'Grado RS2x',
    assinatura: 'Enérgico',
    price: '5.885,00',
    resumo: 'Clássico Grado, fantástico para rock e jazz.',
    buy: 'http://Necessário%20procurar.%20Merece%20a%20busca.',
    review: 'https://youtu.be/RQPqpXbjN3Q'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-80.png',
    alt: 'AudioDream AD8',
    tags: [],
    name: 'AudioDream AD8',
    assinatura: 'Analítico',
    price: '5.900,00',
    resumo: 'Se você quer transparência acima de tudo.',
    buy: 'https://www.audiodream.com.br/products',
    review: 'https://youtu.be/zaR6ONrupG4'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-91.png',
    alt: 'Dunu SA6 MKII',
    tags: [],
    name: 'Dunu SA6 MKII',
    assinatura: 'Musical',
    price: '6.203,00',
    resumo: 'Extremamente melodioso e gostoso de ouvir.',
    buy: 'https://s.click.aliexpress.com/e/_omVbpFr',
    review: 'https://youtu.be/Z1PncT5WTG8'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-8.png',
    alt: 'Apple AirPods Max',
    tags: [],
    name: 'Apple AirPods Max',
    assinatura: 'Natural',
    price: '6.398,00',
    resumo: 'O melhor fone bluetooth com noise-cancelling que já testei, como conjunto.',
    buy: 'https://amzn.to/3GKHe8S',
    review: 'https://youtu.be/BFyawzZ8DOw'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-85.png',
    alt: 'Tanchjim Prism',
    tags: [],
    name: 'Tanchjim Prism',
    assinatura: 'Seco/Direto',
    price: '6.498,00',
    resumo: 'Um fone mais direto, mas extremamente claro e encantador.',
    buy: 'https://s.click.aliexpress.com/e/_o2EXHUt',
    review: 'https://youtu.be/nskVzs7TVqA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-87.png',
    alt: 'Unique Melody MestMKII',
    tags: [],
    name: 'Unique Melody Mest MKII',
    assinatura: 'Musical',
    price: '8.000,00',
    resumo: 'Por muito tempo, foi meu IEM favorito. Muito musical.',
    buy: 'https://www.instagram.com/uniquemelodybrasil/',
    review: 'https://youtu.be/xOVePtj61PE'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-7.png',
    alt: 'Focal Bathys',
    tags: [],
    name: 'Focal Bathys',
    assinatura: 'Neutro-Quente',
    price: '8.000,00',
    resumo: 'O melhor som em um fone bluetooth com noise-cancelling que já testei.',
    buy: 'https://www.audiotag.com.br',
    review: 'https://youtu.be/chXVbakXR_4'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-7-1.png',
    alt: 'Stax SR-X1',
    tags: [],
    name: 'Stax SR-X1',
    assinatura: 'Natural',
    price: '8.999,00',
    resumo: 'Por incrível que pareça, um Stax custo-benefício. Som muito natural e detalhado.',
    buy: 'https://edifier.com.br/sistema-de-alto-falantes-stax-srs-x1000.html',
    review: 'https://youtu.be/j2I3x0XU1BU'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-44.png',
    alt: 'Sennheiser IE900',
    tags: [],
    name: 'Sennheiser IE900',
    assinatura: 'V-Shaped Forte',
    price: '10.600,00',
    resumo: 'Fortemente em V, pra quem gosta. Absurdamente detalhado.',
    buy: 'https://br.octoshop.com/products/sennheiser-ie-900',
    review: 'https://youtu.be/M40Uxq2Ny8g'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-78.png',
    alt: 'Thieaudio MonarchMKIII',
    tags: [],
    name: 'Thieaudio Monarch MKIII',
    assinatura: 'Natural',
    price: '10.799,00',
    resumo: 'Natural e envolvente, como o Moonlight Ultra - porém, mais barato e sem as chaves de tuning.',
    buy: 'https://s.click.aliexpress.com/e/_DBDMWwx',
    review: 'https://youtu.be/2U-zGOVm-4c'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-90.png',
    alt: '64Audio U4S',
    tags: [],
    name: '64Audio U4S',
    assinatura: 'Enérgico',
    price: '11.893,00',
    resumo: 'Incrível pra quem quer um fone mais enérgico',
    buy: 'https://www.64audio.com/products/u4s',
    review: 'https://youtu.be/etPOvdNB46M'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-23.png',
    alt: 'Sennheiser HD800S',
    tags: [],
    name: 'Sennheiser HD800S',
    assinatura: 'Analítico',
    price: '13.149,00',
    resumo: 'Ainda um dos melhores fones do mundo. Referência em espacialidade e detalhamento.',
    buy: 'https://amzn.to/3fFOMOC',
    review: 'https://youtu.be/HB6qtvXeUro'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-79.png',
    alt: 'Yanyin MoonlightUltra',
    tags: [],
    name: 'Yanyin Moonlight Ultra',
    assinatura: 'Natural',
    price: '14.082,00',
    resumo: 'Natural, envolvente... fenomenal.',
    buy: 'https://s.click.aliexpress.com/e/_DFI3lUL',
    review: 'https://youtu.be/pMlOtyyow18'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-76.png',
    alt: 'AudioDream SomniumEST',
    tags: [],
    name: 'AudioDream Somnium EST',
    assinatura: 'Natural',
    price: '19.000,00',
    resumo: 'Diferente do MEST MKII - mais preciso, porém menos musical',
    buy: 'https://www.audiodream.com.br/products',
    review: 'https://youtu.be/d4cWBabRGbU'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-22.png',
    alt: 'Meze Liric 2',
    tags: [],
    name: 'Meze Liric 2',
    assinatura: 'Neutro-Frio',
    price: '21.754,00',
    resumo: 'O melhor fone fechado que já testei.',
    buy: 'https://bit.ly/meze-liric-2',
    review: 'https://youtu.be/CjoFrPK8t5g'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-4-1.png',
    alt: 'Meze Poet',
    tags: [],
    name: 'Meze Poet',
    assinatura: 'Natural',
    price: '21.754,00',
    resumo: 'Um dos meus favoritos da Meze - mais natural e envolvente que o próprio Empyrean 2.',
    buy: 'https://mezeaudio.com/products/poet?_ef_transaction_id=&amp;oid=48&amp;affid=12',
    review: 'https://youtu.be/ni0hmhuT37A'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-81.png',
    alt: 'Unique MelodyMultiverse Mentor',
    tags: [],
    name: 'Unique Melody Multiverse Mentor',
    assinatura: 'Neutro-Quente',
    price: '24.000,00',
    resumo: 'Junta o refinamento do MEST a uma pegada mais quente e presente.',
    buy: 'https://www.instagram.com/uniquemelodybrasil/',
    review: 'https://youtu.be/bMfFkeu66k0'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-55.png',
    alt: '64Audio Volür',
    tags: [],
    name: '64Audio Volür',
    assinatura: 'Enérgico',
    price: '27.226,00',
    resumo: 'O ápice da sonoridade energética.',
    buy: 'https://www.64audio.com/products/volur/',
    review: 'https://youtu.be/Sd3ZzgAmkSA'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-54.png',
    alt: 'Moondrop Solis 2',
    tags: [],
    name: 'Moondrop Solis 2',
    assinatura: 'Natural',
    price: '30.498,00',
    resumo: 'O melhor intra-auricular que já ouvi até hoje. Ápice da naturalidade.',
    buy: 'https://s.click.aliexpress.com/e/_oFKrOcd',
    review: 'https://youtu.be/kuhkDgt40jk'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-21.png',
    alt: 'Meze Empyrean II',
    tags: [],
    name: 'Meze Empyrean II',
    assinatura: 'Natural',
    price: '32.687,00',
    resumo: 'Um fone excepcionalmente natural, ao mesmo tempo em que é musical.',
    buy: 'https://mezeaudio.com/products/empyrean2?_ef_transaction_id=&amp;oid=32&amp;affid=12',
    review: 'https://youtu.be/LnXoN_Aeeuk'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-20.png',
    alt: 'Stax SR-009S',
    tags: [],
    name: 'Stax SR-009S',
    assinatura: 'Analítico',
    price: '39.999,00',
    resumo: 'Transparência, detalhamento e linearidade máximos',
    buy: 'https://bit.ly/45GhbMF',
    review: 'https://youtu.be/728RMJtU2VQ'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-19.png',
    alt: 'Focal Utopia 2022',
    tags: [],
    name: 'Focal Utopia 2022',
    assinatura: 'Neutro-Quente',
    price: '40.000,00',
    resumo: 'Um HD600 elevado à máxima potência. Absurdamente natural e técnico.',
    buy: 'https://www.audiotag.com.br/produtos?q=utopia',
    review: 'https://youtu.be/lanT5yLmWgc'
  },
  {
    img: 'http://mindtheheadphone.com.br/wp-content/uploads/2025/06/arquivofinal_Prancheta-1-copia-18.png',
    alt: 'Stax SR-X9000',
    tags: [],
    name: 'Stax SR-X9000',
    assinatura: 'Neutro-Frio',
    price: '49.000,00',
    resumo: 'Ainda mais transparente e detalhado que o SR-009S, ao mesmo tempo em que é mais musical - porém, não muito.',
    buy: 'https://edifier.com.br/earspeakers-stax-sr-x9000.html',
    review: 'https://youtu.be/7du9oDkHdSA'
  }
]
